### ISSUE TITLE
Torque Sensor Problemi

### ISSUE THREAD

**Issue by MustafaMuratSezer** [odtu/project-0-MustafaMuratSezer#1]
Hocam merhaba, Torque ölçümü yapmak için sistemime ideal torque sensor ekledim. Ancak bu sensoru ekledikten sonra hız olarak scope ta hep 0 görüyorum. Torque sensoru kaldırdıktan sonra beklediğim hız sonuçlarını alıyorum. Neden aynı anda torque hız ve akım değerlerini alamıyorum merak ettim ve size sormak istedim. Ek olarak, torque ölçümü yaptığım zamanda azalan bir torque eğrisi alıyorum. Bunun doğru olmadığını düşünüyorum çünkü normal hız eğrimde hızım azalıyor bununda torque arttırması gerekir diye düşünüyorum. Nerede hata yapıyorum sormak istedim. Teşekkürler

**Comment by ozank** [comment]
Şurda anlatıldığı gibi seri paralel bağlamayla ilgili bir durum olabilir diye tahmin ediyorum, ama dosyayı açıp bakamadım.

https://www.mathworks.com/matlabcentral/answers/271819-ideal-torque-and-rotational-motion-sensors

@mesutto fırsatın olduğu zaman bir bakabilir misin?
